version: '3.8'

services:
  reverse_proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - 80:80
      - 8001:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  web:
    build: .
    labels:
      - "traefik.http.routers.web.rule=Host(`localhost`) "

  api:
    build:
      context: ../app
    labels:
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"

