version: '3.8'

services:
  web:
    build: web-static
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.routers.web.tls=true"
    deploy:
      replicas: 5

  api:
    build:
      context: ../app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=7000"
      - "traefik.http.services.api.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.api.loadbalancer.sticky.cookie.name=cookieapi"
      - "traefik.http.services.api.loadbalancer.sticky.cookie.secure=true"
      - "traefik.http.routers.api.tls=true"
    deploy:
      replicas: 5

  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true  # Enable Traefik dashboard
      - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certificates:/app/certificates
      - ./traefik.yml:/etc/traefik/traefik.yml
    ports:
      - "80:80" # web static & api
      - "8080:8080" # Traefik dashboard
      - "443:443" # HTTPS port